INSERT INTO pokemon_forms (pokemon_id, id, name, shiny_locked) VALUES
('venusaur', 'f', 'Female', 0),
('venusaur', 'gmax', 'Gmax', 0),
('charizard', 'gmax', 'Gmax', 0),
('blastoise', 'gmax', 'Gmax', 0),
('butterfree', 'f', 'Female', 0),
('butterfree', 'gmax', 'Gmax', 0),
('rattata', 'f', 'Female', 0),
('rattata', 'alola', 'Alola', 0),
('raticate', 'f', 'Female', 0),
('raticate', 'alola', 'Alola', 0),
('pikachu', 'f', 'Female', 0),
('pikachu', 'gmax', 'Gmax', 0),
('pikachu', 'original', 'Original', 0),
('pikachu', 'hoenn', 'Hoenn', 0),
('pikachu', 'sinnoh', 'Sinnoh', 0),
('pikachu', 'unova', 'Unova', 0),
('pikachu', 'kalos', 'Kalos', 0),
('pikachu', 'alola', 'Alola', 0),
('pikachu', 'partner', 'Partner', 0),
('pikachu', 'world', 'World', 0),
('raichu', 'f', 'Female', 0),
('raichu', 'alola', 'Alola', 0),
('sandshrew', 'alola', 'Alola', 0),
('sandslash', 'alola', 'Alola', 0),
('vulpix', 'alola', 'Alola', 0),
('ninetales', 'alola', 'Alola', 0),
('zubat', 'f', 'Female', 0),
('golbat', 'f', 'Female', 0),
('gloom', 'f', 'Female', 0),
('vileplume', 'f', 'Female', 0),
('diglett', 'alola', 'Alola', 0),
('dugtrio', 'alola', 'Alola', 0),
('meowth', 'alola', 'Alola', 0),
('meowth', 'galar', 'Galar', 0),
('meowth', 'gmax', 'Gmax', 0),
('persian', 'alola', 'Alola', 0),
('growlithe', 'hisui', 'Hisui', 0),
('arcanine', 'hisui', 'Hisui', 0),
('kadabra', 'f', 'Female', 0),
('alakazam', 'f', 'Female', 0),
('machamp', 'gmax', 'Gmax', 0),
('geodude', 'alola', 'Alola', 0),
('graveler', 'alola', 'Alola', 0),
('golem', 'alola', 'Alola', 0),
('ponyta', 'galar', 'Galar', 0),
('rapidash', 'galar', 'Galar', 0),
('slowpoke', 'galar', 'Galar', 0),
('slowbro', 'galar', 'Galar', 0),
('farfetchd', 'galar', 'Galar', 0),
('doduo', 'f', 'Female', 0),
('dodrio', 'f', 'Female', 0),
('grimer', 'alola', 'Alola', 0),
('muk', 'alola', 'Alola', 0),
('gengar', 'gmax', 'Gmax', 0),
('hypno', 'f', 'Female', 0),
('kingler', 'gmax', 'Gmax', 0),
('voltorb', 'hisui', 'Hisui', 0),
('electrode', 'hisui', 'Hisui', 0),
('exeggutor', 'alola', 'Alola', 0),
('marowak', 'alola', 'Alola', 0),
('weezing', 'galar', 'Galar', 0),
('rhyhorn', 'f', 'Female', 0),
('rhydon', 'f', 'Female', 0),
('goldeen', 'f', 'Female', 0),
('seaking', 'f', 'Female', 0),
('mrmime', 'galar', 'Galar', 0),
('scyther', 'f', 'Female', 0),
('tauros', 'paldea', 'Paldea', 0),
('tauros', 'paldea-fire', 'Paldea Fire', 0),
('tauros', 'paldea-water', 'Paldea Water', 0),
('magikarp', 'f', 'Female', 0),
('gyarados', 'f', 'Female', 0),
('lapras', 'gmax', 'Gmax', 0),
('eevee', 'f', 'Female', 0),
('eevee', 'gmax', 'Gmax', 0),
('snorlax', 'gmax', 'Gmax', 0),
('articuno', 'galar', 'Galar', 0),
('zapdos', 'galar', 'Galar', 0),
('moltres', 'galar', 'Galar', 0),
('meganium', 'f', 'Female', 0),
('typhlosion', 'hisui', 'Hisui', 0),
('ledyba', 'f', 'Female', 0),
('ledian', 'f', 'Female', 0),
('xatu', 'f', 'Female', 0),
('sudowoodo', 'f', 'Female', 0),
('politoed', 'f', 'Female', 0),
('aipom', 'f', 'Female', 0),
('wooper', 'f', 'Female', 0),
('wooper', 'paldea', 'Paldea', 0),
('quagsire', 'f', 'Female', 0),
('murkrow', 'f', 'Female', 0),
('slowking', 'galar', 'Galar', 0),
('unown', 'b', 'B', 0),
('unown', 'c', 'C', 0),
('unown', 'd', 'D', 0),
('unown', 'e', 'E', 0),
('unown', 'f', 'F', 0),
('unown', 'g', 'G', 0),
('unown', 'h', 'H', 0),
('unown', 'i', 'I', 0),
('unown', 'j', 'J', 0),
('unown', 'k', 'K', 0),
('unown', 'l', 'L', 0),
('unown', 'm', 'M', 0),
('unown', 'n', 'N', 0),
('unown', 'o', 'O', 0),
('unown', 'p', 'P', 0),
('unown', 'q', 'Q', 0),
('unown', 'r', 'R', 0),
('unown', 's', 'S', 0),
('unown', 't', 'T', 0),
('unown', 'u', 'U', 0),
('unown', 'v', 'V', 0),
('unown', 'w', 'W', 0),
('unown', 'x', 'X', 0),
('unown', 'y', 'Y', 0),
('unown', 'z', 'Z', 0),
('unown', 'exclamation', 'Exclamation', 0),
('unown', 'question', 'Question', 0),
('wobbuffet', 'f', 'Female', 0),
('girafarig', 'f', 'Female', 0),
('gligar', 'f', 'Female', 0),
('steelix', 'f', 'Female', 0),
('qwilfish', 'hisui', 'Hisui', 0),
('scizor', 'f', 'Female', 0),
('heracross', 'f', 'Female', 0),
('sneasel', 'f', 'Female', 0),
('sneasel', 'hisui', 'Hisui', 0),
('sneasel', 'hisui-f', 'Hisui Female', 0),
('ursaring', 'f', 'Female', 0),
('piloswine', 'f', 'Female', 0),
('corsola', 'galar', 'Galar', 0),
('octillery', 'f', 'Female', 0),
('houndoom', 'f', 'Female', 0),
('donphan', 'f', 'Female', 0),
('torchic', 'f', 'Female', 0),
('combusken', 'f', 'Female', 0),
('blaziken', 'f', 'Female', 0),
('zigzagoon', 'galar', 'Galar', 0),
('linoone', 'galar', 'Galar', 0),
('beautifly', 'f', 'Female', 0),
('dustox', 'f', 'Female', 0),
('ludicolo', 'f', 'Female', 0),
('nuzleaf', 'f', 'Female', 0),
('shiftry', 'f', 'Female', 0),
('meditite', 'f', 'Female', 0),
('medicham', 'f', 'Female', 0),
('roselia', 'f', 'Female', 0),
('gulpin', 'f', 'Female', 0),
('swalot', 'f', 'Female', 0),
('numel', 'f', 'Female', 0),
('camerupt', 'f', 'Female', 0),
('cacturne', 'f', 'Female', 0),
('milotic', 'f', 'Female', 0),
('relicanth', 'f', 'Female', 0),
('kyogre', 'primal', 'Primal', 0),
('groudon', 'primal', 'Primal', 0),
('deoxys', 'attack', 'Attack', 0),
('deoxys', 'defense', 'Defense', 0),
('deoxys', 'speed', 'Speed', 0),
('starly', 'f', 'Female', 0),
('staravia', 'f', 'Female', 0),
('staraptor', 'f', 'Female', 0),
('bidoof', 'f', 'Female', 0),
('bibarel', 'f', 'Female', 0),
('kricketot', 'f', 'Female', 0),
('kricketune', 'f', 'Female', 0),
('shinx', 'f', 'Female', 0),
('luxio', 'f', 'Female', 0),
('luxray', 'f', 'Female', 0),
('roserade', 'f', 'Female', 0),
('burmy', 'sandy', 'Sandy', 0),
('burmy', 'trash', 'Trash', 0),
('wormadam', 'sandy', 'Sandy', 0),
('wormadam', 'trash', 'Trash', 0),
('combee', 'f', 'Female', 0),
('pachirisu', 'f', 'Female', 0),
('buizel', 'f', 'Female', 0),
('floatzel', 'f', 'Female', 0),
('cherrim', 'sunshine', 'Sunshine', 0),
('shellos', 'east', 'East', 0),
('gastrodon', 'east', 'East', 0),
('ambipom', 'f', 'Female', 0),
('gible', 'f', 'Female', 0),
('gabite', 'f', 'Female', 0),
('garchomp', 'f', 'Female', 0),
('hippopotas', 'f', 'Female', 0),
('hippowdon', 'f', 'Female', 0),
('croagunk', 'f', 'Female', 0),
('toxicroak', 'f', 'Female', 0),
('finneon', 'f', 'Female', 0),
('lumineon', 'f', 'Female', 0),
('snover', 'f', 'Female', 0),
('abomasnow', 'f', 'Female', 0),
('weavile', 'f', 'Female', 0),
('rhyperior', 'f', 'Female', 0),
('tangrowth', 'f', 'Female', 0),
('mamoswine', 'f', 'Female', 0),
('rotom', 'heat', 'Heat', 0),
('rotom', 'wash', 'Wash', 0),
('rotom', 'frost', 'Frost', 0),
('rotom', 'fan', 'Fan', 0),
('rotom', 'mow', 'Mow', 0),
('dialga', 'origin', 'Origin', 0),
('palkia', 'origin', 'Origin', 0),
('giratina', 'origin', 'Origin', 0),
('shaymin', 'sky', 'Sky', 0),
('samurott', 'hisui', 'Hisui', 0),
('unfezant', 'f', 'Female', 0),
('lilligant', 'hisui', 'Hisui', 0),
('basculin', 'blue-striped', 'Blue Striped', 0),
('basculin', 'white-striped', 'White Striped', 0),
('darumaka', 'galar', 'Galar', 0),
('darmanitan', 'zen', 'Zen', 0),
('darmanitan', 'galar', 'Galar', 0),
('darmanitan', 'galar-zen', 'Galar Zen', 0),
('yamask', 'galar', 'Galar', 0),
('garbodor', 'gmax', 'Gmax', 0),
('zorua', 'hisui', 'Hisui', 0),
('zoroark', 'hisui', 'Hisui', 0),
('deerling', 'summer', 'Summer', 0),
('deerling', 'autumn', 'Autumn', 0),
('deerling', 'winter', 'Winter', 0),
('sawsbuck', 'summer', 'Summer', 0),
('sawsbuck', 'autumn', 'Autumn', 0),
('sawsbuck', 'winter', 'Winter', 0),
('frillish', 'f', 'Female', 0),
('jellicent', 'f', 'Female', 0),
('stunfisk', 'galar', 'Galar', 0),
('braviary', 'hisui', 'Hisui', 0),
('tornadus', 'therian', 'Therian', 0),
('thundurus', 'therian', 'Therian', 0),
('landorus', 'therian', 'Therian', 0),
('keldeo', 'resolute', 'Resolute', 1),
('greninja', 'battle-bond', 'Battle Bond', 1),
('vivillon', 'meadow', 'Meadow', 0),
('vivillon', 'polar', 'Polar', 0),
('vivillon', 'tundra', 'Tundra', 0),
('vivillon', 'continental', 'Continental', 0),
('vivillon', 'garden', 'Garden', 0),
('vivillon', 'elegant', 'Elegant', 0),
('vivillon', 'modern', 'Modern', 0),
('vivillon', 'marine', 'Marine', 0),
('vivillon', 'archipelago', 'Archipelago', 0),
('vivillon', 'high-plains', 'High Plains', 0),
('vivillon', 'sandstorm', 'Sandstorm', 0),
('vivillon', 'river', 'River', 0),
('vivillon', 'monsoon', 'Monsoon', 0),
('vivillon', 'savanna', 'Savanna', 0),
('vivillon', 'sun', 'Sun', 0),
('vivillon', 'ocean', 'Ocean', 0),
('vivillon', 'jungle', 'Jungle', 0),
('vivillon', 'fancy', 'Fancy', 0),
('vivillon', 'pokeball', 'Pokeball', 0),
('pyroar', 'f', 'Female', 0),
('flabebe', 'blue', 'Blue', 0),
('flabebe', 'orange', 'Orange', 0),
('flabebe', 'white', 'White', 0),
('flabebe', 'yellow', 'Yellow', 0),
('floette', 'blue', 'Blue', 0),
('floette', 'orange', 'Orange', 0),
('floette', 'white', 'White', 0),
('floette', 'yellow', 'Yellow', 0),
('florges', 'blue', 'Blue', 0),
('florges', 'orange', 'Orange', 0),
('florges', 'white', 'White', 0),
('florges', 'yellow', 'Yellow', 0),
('furfrou', 'heart', 'Heart', 0),
('furfrou', 'star', 'Star', 0),
('furfrou', 'diamond', 'Diamond', 0),
('furfrou', 'debutante', 'Debutante', 0),
('furfrou', 'matron', 'Matron', 0),
('furfrou', 'dandy', 'Dandy', 0),
('furfrou', 'la-reine', 'La Reine', 0),
('furfrou', 'kabuki', 'Kabuki', 0),
('furfrou', 'pharaoh', 'Pharaoh', 0),
('meowstic', 'f', 'Female', 0),
('aegislash', 'blade', 'Blade', 0),
('sliggoo', 'hisui', 'Hisui', 0),
('goodra', 'hisui', 'Hisui', 0),
('pumpkaboo', 'small', 'Small', 0),
('pumpkaboo', 'large', 'Large', 0),
('pumpkaboo', 'super', 'Super', 0),
('gourgeist', 'small', 'Small', 0),
('gourgeist', 'large', 'Large', 0),
('gourgeist', 'super', 'Super', 0),
('avalugg', 'hisui', 'Hisui', 0),
('xerneas', 'active', 'Active', 0),
('zygarde', '10', '10', 0),
('zygarde', 'complete', 'Complete', 0),
('hoopa', 'unbound', 'Unbound', 1),
('decidueye', 'hisui', 'Hisui', 0),
('oricorio', 'pom-pom', 'Pom Pom', 0),
('oricorio', 'pau', 'Pau', 0),
('oricorio', 'sensu', 'Sensu', 0),
('rockruff', 'own-tempo', 'Own Tempo', 0),
('lycanroc', 'midnight', 'Midnight', 0),
('lycanroc', 'dusk', 'Dusk', 0),
('wishiwashi', 'school', 'School', 0),
('minior', 'red', 'Red', 0),
('minior', 'orange', 'Orange', 0),
('minior', 'yellow', 'Yellow', 0),
('minior', 'green', 'Green', 0),
('minior', 'blue', 'Blue', 0),
('minior', 'indigo', 'Indigo', 0),
('minior', 'violet', 'Violet', 0),
('mimikyu', 'busted', 'Busted', 0),
('necrozma', 'dusk-mane', 'Dusk Mane', 0),
('necrozma', 'dawn-wings', 'Dawn Wings', 0),
('necrozma', 'ultra', 'Ultra', 0),
('magearna', 'original', 'Original', 1),
('melmetal', 'gmax', 'Gmax', 0),
('rillaboom', 'gmax', 'Gmax', 0),
('cinderace', 'gmax', 'Gmax', 0),
('inteleon', 'gmax', 'Gmax', 0),
('corviknight', 'gmax', 'Gmax', 0),
('orbeetle', 'gmax', 'Gmax', 0),
('drednaw', 'gmax', 'Gmax', 0),
('coalossal', 'gmax', 'Gmax', 0),
('flapple', 'gmax', 'Gmax', 0),
('appletun', 'gmax', 'Gmax', 0),
('sandaconda', 'gmax', 'Gmax', 0),
('cramorant', 'gulping', 'Gulping', 0),
('cramorant', 'gorging', 'Gorging', 0),
('toxtricity', 'low-key', 'Low Key', 0),
('toxtricity', 'gmax', 'Gmax', 0),
('toxtricity', 'low-key-gmax', 'Low Key Gmax', 0),
('centiskorch', 'gmax', 'Gmax', 0),
('sinistea', 'antique', 'Antique', 0),
('polteageist', 'antique', 'Antique', 0),
('hatterene', 'gmax', 'Gmax', 0),
('grimmsnarl', 'gmax', 'Gmax', 0),
('alcremie', 'vanilla-cream-berry', 'Vanilla Cream Berry', 0),
('alcremie', 'vanilla-cream-love', 'Vanilla Cream Love', 0),
('alcremie', 'vanilla-cream-star', 'Vanilla Cream Star', 0),
('alcremie', 'vanilla-cream-clover', 'Vanilla Cream Clover', 0),
('alcremie', 'vanilla-cream-flower', 'Vanilla Cream Flower', 0),
('alcremie', 'vanilla-cream-ribbon', 'Vanilla Cream Ribbon', 0),
('alcremie', 'ruby-cream-strawberry', 'Ruby Cream Strawberry', 0),
('alcremie', 'ruby-cream-berry', 'Ruby Cream Berry', 0),
('alcremie', 'ruby-cream-love', 'Ruby Cream Love', 0),
('alcremie', 'ruby-cream-star', 'Ruby Cream Star', 0),
('alcremie', 'ruby-cream-clover', 'Ruby Cream Clover', 0),
('alcremie', 'ruby-cream-flower', 'Ruby Cream Flower', 0),
('alcremie', 'ruby-cream-ribbon', 'Ruby Cream Ribbon', 0),
('alcremie', 'matcha-cream-strawberry', 'Matcha Cream Strawberry', 0),
('alcremie', 'matcha-cream-berry', 'Matcha Cream Berry', 0),
('alcremie', 'matcha-cream-love', 'Matcha Cream Love', 0),
('alcremie', 'matcha-cream-star', 'Matcha Cream Star', 0),
('alcremie', 'matcha-cream-clover', 'Matcha Cream Clover', 0),
('alcremie', 'matcha-cream-flower', 'Matcha Cream Flower', 0),
('alcremie', 'matcha-cream-ribbon', 'Matcha Cream Ribbon', 0),
('alcremie', 'mint-cream-strawberry', 'Mint Cream Strawberry', 0),
('alcremie', 'mint-cream-berry', 'Mint Cream Berry', 0),
('alcremie', 'mint-cream-love', 'Mint Cream Love', 0),
('alcremie', 'mint-cream-star', 'Mint Cream Star', 0),
('alcremie', 'mint-cream-clover', 'Mint Cream Clover', 0),
('alcremie', 'mint-cream-flower', 'Mint Cream Flower', 0),
('alcremie', 'mint-cream-ribbon', 'Mint Cream Ribbon', 0),
('alcremie', 'lemon-cream-strawberry', 'Lemon Cream Strawberry', 0),
('alcremie', 'lemon-cream-berry', 'Lemon Cream Berry', 0),
('alcremie', 'lemon-cream-love', 'Lemon Cream Love', 0),
('alcremie', 'lemon-cream-star', 'Lemon Cream Star', 0),
('alcremie', 'lemon-cream-clover', 'Lemon Cream Clover', 0),
('alcremie', 'lemon-cream-flower', 'Lemon Cream Flower', 0),
('alcremie', 'lemon-cream-ribbon', 'Lemon Cream Ribbon', 0),
('alcremie', 'salted-cream-strawberry', 'Salted Cream Strawberry', 0),
('alcremie', 'salted-cream-berry', 'Salted Cream Berry', 0),
('alcremie', 'salted-cream-love', 'Salted Cream Love', 0),
('alcremie', 'salted-cream-star', 'Salted Cream Star', 0),
('alcremie', 'salted-cream-clover', 'Salted Cream Clover', 0),
('alcremie', 'salted-cream-flower', 'Salted Cream Flower', 0),
('alcremie', 'salted-cream-ribbon', 'Salted Cream Ribbon', 0),
('alcremie', 'ruby-swirl-strawberry', 'Ruby Swirl Strawberry', 0),
('alcremie', 'ruby-swirl-berry', 'Ruby Swirl Berry', 0),
('alcremie', 'ruby-swirl-love', 'Ruby Swirl Love', 0),
('alcremie', 'ruby-swirl-star', 'Ruby Swirl Star', 0),
('alcremie', 'ruby-swirl-clover', 'Ruby Swirl Clover', 0),
('alcremie', 'ruby-swirl-flower', 'Ruby Swirl Flower', 0),
('alcremie', 'ruby-swirl-ribbon', 'Ruby Swirl Ribbon', 0),
('alcremie', 'caramel-swirl-strawberry', 'Caramel Swirl Strawberry', 0),
('alcremie', 'caramel-swirl-berry', 'Caramel Swirl Berry', 0),
('alcremie', 'caramel-swirl-love', 'Caramel Swirl Love', 0),
('alcremie', 'caramel-swirl-star', 'Caramel Swirl Star', 0),
('alcremie', 'caramel-swirl-clover', 'Caramel Swirl Clover', 0),
('alcremie', 'caramel-swirl-flower', 'Caramel Swirl Flower', 0),
('alcremie', 'caramel-swirl-ribbon', 'Caramel Swirl Ribbon', 0),
('alcremie', 'rainbow-swirl-strawberry', 'Rainbow Swirl Strawberry', 0),
('alcremie', 'rainbow-swirl-berry', 'Rainbow Swirl Berry', 0),
('alcremie', 'rainbow-swirl-love', 'Rainbow Swirl Love', 0),
('alcremie', 'rainbow-swirl-star', 'Rainbow Swirl Star', 0),
('alcremie', 'rainbow-swirl-clover', 'Rainbow Swirl Clover', 0),
('alcremie', 'rainbow-swirl-flower', 'Rainbow Swirl Flower', 0),
('alcremie', 'rainbow-swirl-ribbon', 'Rainbow Swirl Ribbon', 0),
('alcremie', 'gmax', 'Gmax', 0),
('eiscue', 'noice', 'Noice', 0),
('indeedee', 'f', 'Female', 0),
('morpeko', 'hangry', 'Hangry', 0),
('copperajah', 'gmax', 'Gmax', 0),
('duraludon', 'gmax', 'Gmax', 0),
('urshifu', 'rapid-strike', 'Rapid Strike', 1),
('urshifu', 'gmax', 'Gmax', 1),
('urshifu', 'rapid-strike-gmax', 'Rapid Strike GMax', 1),
('zarude', 'dada', 'Dada', 1),
('calyrex', 'ice', 'Ice', 1),
('calyrex', 'shadow', 'Shadow', 1),
('ursaluna', 'bloodmoon', 'Bloodmoon', 1),
('basculegion', 'f', 'Female', 0),
('enamorus', 'therian', 'Therian', 1),
('oinkologne', 'f', 'Female', 0),
('maushold', 'three', 'Three', 0),
('squawkabilly', 'blue', 'Blue', 0),
('squawkabilly', 'yellow', 'Yellow', 0),
('squawkabilly', 'white', 'White', 0),
('palafin', 'hero', 'Hero', 0),
('tatsugiri', 'droopy', 'Droopy', 0),
('tatsugiri', 'stretchy', 'Stretchy', 0),
('dudunsparce', 'three-segment', 'Three Segment', 0),
('gimmighoul', 'roaming', 'Roaming', 1),
('poltchageist', 'artisan', 'Artisan', 0),
('sinistcha', 'masterpiece', 'Masterpiece', 0)
;