name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DB_PATH: "file:shinidex.db"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24']

    steps:
    - uses: actions/checkout@v3

    - name: Generate AUTH_KEY
      run: echo "AUTH_KEY=$(openssl rand -base64 32)" >> $GITHUB_ENV

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Install templ
      run: go install github.com/a-h/templ/cmd/templ@latest

    - name: Generate 
      run: go generate ./...

    - name: Run tests
      run: go test -v -timeout 30s ./...

    - name: Build
      run: go build -o shinidex -v ./cmd/...

